force pipeline

diff --git a/.github/workflows/pipeline.yaml b/.github/workflows/pipeline.yaml
--- a/.github/workflows/pipeline.yaml
+++ b/.github/workflows/pipeline.yaml
@@ -55,6 +55,7 @@ jobs:
         run: npm run test
 
 
+  
   deploy:
     name: Deploy Phase
     runs-on: ubuntu-latest
@@ -80,13 +81,17 @@ jobs:
 
       - name: Prepare Google Application Credentials
         run: |
-         echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode --ignore-garbage > $HOME/private-key.json
-         if [ ! -s $HOME/private-key.json ]; then echo "Error: private-key.json is empty"; exit 1; fi
+          echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}" | base64 --decode --ignore-garbage > $HOME/private-key.json
+
+      - name: Debug - File Structure Check
+        run: |
+          echo "--- Current Directory Content ---"
+          ls -F
+          echo "--- dist Directory Content ---"
+          ls -F dist/ || echo "dist folder missing!"
 
       - name: Deploy Firebase
         run: |
-          ls -R dist/
-          
           export GOOGLE_APPLICATION_CREDENTIALS=$HOME/private-key.json
           firebase experiments:disable webframeworks
           firebase deploy --only hosting --project study-record-a2d90 --debug
